// Generated by CoffeeScript 1.8.0
var app, bodyParser, compression, cookieParser, express, logger, mongoose, passport, session;

express = require("express");

mongoose = require("mongoose");

logger = require("morgan");

passport = require("passport");

cookieParser = require("cookie-parser");

bodyParser = require("body-parser");

session = require("express-session");

compression = require("compression");

app = express();

app.use(logger("dev"));

app.use(compression());

app.use(express["static"]("../public"));

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(cookieParser());

app.use(bodyParser.json());

app.use(session({
  secret: "keyboard cat",
  resave: false,
  saveUninitialized: true
}));

app.use(passport.initialize());

app.use(passport.session());

app.get("/dev", function(req, res) {
  return res.render("dev/index", doc);
});

app.get("/deploy", function(req, res) {
  return res.render("deploy/index", doc);
});

app.listen(3030);

console.log("Express server started on port 3030");
